### ISSUE TITLE
Compilation error: ApplyCACorrect not found

### ISSUE THREAD

**Issue by Thanatomanic** [butcherg/rawproc#21]
Hi Glenn! I just wanted to compile the latest build of rawproc, but I ran into a compilation error. My system: Windows 10 using MSYS2. I followed your build instructions (I think to the letter...), and compile as follows:
```
../configure --with-wx-config=/home/Me/wxWidgets-3.1.3/build-msys2/wx-config CXXFLAGS=-O3
make
```
So no fancy stuff with lensfun or librtprocess. However I get this:

```
../../src/gimage_cmd.cpp: In function 'std::string do_cmd(gImage&, std::string, std::string, bool)':
../../src/gimage_cmd.cpp:398:8: error: 'class gImage' has no member named 'ApplyCACorrect'
  398 |    dib.ApplyCACorrect(threadcount);
      |        ^~~~~~~~~~~~~~
../../src/gimage_cmd.cpp:415:8: error: 'class gImage' has no member named 'ApplyHLRecover'
  415 |    dib.ApplyHLRecover(threadcount);
      |        ^~~~~~~~~~~~~~
make[1]: *** [Makefile:678: gimage_cmd.o] Error 1
```
Any thoughts what's going on?

**Comment by butcherg** [comment]
Ack, missed a preprocessor conditional...

Those are librtprocess functions, added later, after the original demosaic functions. 'pull master' again, and you'll get the commit I just made to add that conditional.

Let me know how it goes; I don't have a clone on this computer to test USELIBRTPROCESS=false...

**Comment by Thanatomanic** [comment]
I see! There's two more instances:
https://github.com/butcherg/rawproc/blob/190d2ed2d7658cd4ba3d35f37cc9010e759cae94/src/PicProcessorCACorrect.cpp#L245
and
https://github.com/butcherg/rawproc/blob/190d2ed2d7658cd4ba3d35f37cc9010e759cae94/src/PicProcessorHLRecover.cpp#L134

**Comment by butcherg** [comment]
Okay, pull master again...

**Comment by Thanatomanic** [comment]
I don't see a new commit :-)

**Comment by butcherg** [comment]
oh, for every pull there must first be push...  :)

It's there now.

**Comment by Thanatomanic** [comment]
Fixed!

**Comment by paolodepetrillo** [comment]
I think there's been a regression of this issue, trying to build the current master without librtprocess fails because of a call to ApplyHLRecover without any preprocessor conditional.

**Comment by butcherg** [comment]
Apologies, someone else discovered this a couple of months ago and I've forgotten to deal with it.  I have to do yard work today, but I'll push a fix to master tonight (my time, USA Mountain Daylight)

Are you working with a git clone, or the source tar.gz?

**Comment by paolodepetrillo** [comment]
I had been building from a git clone on master branch, but I've just switched to the AppImage. Originally I was building from source because I couldn't get the AppImage to run on an up to date Arch Linux system (error "undefined symbol: g_memdup2"). But if I mount the AppImage filesystem and run the executable directly outside of the AppImage environment it works.

**Comment by butcherg** [comment]
Just pushed a884a7, which wraps the dib.ApplyHLRecover() call in gimage_process.cpp with the USE_LIBRTPROCESS pre-processor conditional.

Funny, I was thinking of removing that conditional as I believe librtprocess is now a rather substantial part of rawproc, but it turns out there are a number of folk apparently relying on it to make their initial compilation endeavor a bit easier...
