### ISSUE TITLE
Assert "item.IsOk()" failed in GetItemText(): invalid tree item

### ISSUE THREAD

**Issue by Thanatomanic** [butcherg/rawproc#22]
Got another one for you. After successful compilation, every time I try to open a file I get the same error after which rawproc dies.

![image](https://user-images.githubusercontent.com/6567747/76859265-40fe3100-6859-11ea-9fa6-e99649649591.png)

Is there any more information I could supply to help you figuring out what's going on?

**Comment by butcherg** [comment]
Hmmm, interesting...  I found a copy of amsterdam.pef, and it opens okay on my build.  I think I'd need a backtrace from gdb...

**Comment by Thanatomanic** [comment]
Sure thing, I hope simply setting `CXXFLAGS=-g` does the trick for a debug build.

This is my stack trace. Interestingly, a lot of warnings are generated too when opening the file browser when opening a file. I guess those can be ignored.

[debuglog.txt](https://github.com/butcherg/rawproc/files/4343749/debuglog.txt)

**Comment by butcherg** [comment]
Thanks, your debug log pointed to a rawproc event handler in which I wasn't checking a tree item to see if it was ok before using it.  I changed that event to do so, compiled and tested, and pushed the commit to master.

Noticed you're using wxWidgets as a .dll.  I haven't used it any way but static in either linux or windows, so I'll be interested in other things you see.  I surmise the above error never manifest because of timing differences between static and dynamic libraries and event handling...

Thanks!

**Comment by Thanatomanic** [comment]
Fix confirmed!

> Noticed you're using wxWidgets as a .dll. I haven't used it any way but static in either linux or windows, so I'll be interested in other things you see. I surmise the above error never manifest because of timing differences between static and dynamic libraries and event handling...

I wasn't aware I did. I followed your build instructions for wxWidgets, so I assumed things were static. Hmmm... Not that it really matters, things work now :+1:
